enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGNUP_SCREEN = 'SIGNUP_SCREEN',
  PASSWORD_RESET = 'PASSWORD_RESET',
  CREATE_PASSWORD = 'CREATE_PASSWORD',
  OTP_SCREEN = 'OTP_SCREEN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  IngredientScreen = 'IngredientScreen',

  BOTTOM_TAB = 'BOTTOM_TAB',
  RecipeList = 'RecipeList',
  MealPlanPreferences = 'MealPlanPreferences',
  MealPlan = 'MealPlan',
  CreateMealPlan = 'CreateMealPlan',
  EditMeals = 'EditMeals',
  ViewmealPlaning = 'ViewmealPlaning',
  CookBookList = 'CookBookList',
  CookBookDetails = 'CookBookDetails',
  GroceryDetailsEdit = 'GroceryDetailsEdit',
  GroceryListForm = 'GroceryListForm',
  MainDrawer = 'MainDrawer',
  Subscription = 'Subscription',
  Profile = 'Profile',
  Personal_preferences = 'Personal_preferences',
  create_cookbook = 'create cookbook',
  Timer_ringtone = 'Timer_ringtone',
  Change_Username = 'Change_Username',
  Change_Password = 'Change Password',
  Privacy_Settings = 'Privacy_Settings',
  Termsconditions = 'Termsconditions',
  Privacypolicy = 'Privacypolicy',
  FrequentlyQuestions = 'FrequentlyQuestions',
  NOTIFICATION ='NOTIFICATION',
  SubscriptionOption='SubscriptionOption',
  ShareHackAplate='ShareHackAplate',
  RingtoneMenu='RingtoneMenu',
  NotificationDetails='NotificationDetails',
  ShareMessage='ShareMessage'
}

export default ScreenNameEnum;
