export const image={
   appLogo:require('../../assets/croping/LOGO3x.png'),
   Lock:require('../../assets/croping/Lock-2.png'),
   email:require('../../assets/croping/Email.png'),
   eye:require('../../assets/croping/Hide2.png'),
   google:require('../../assets/croping/google.png'),
   user:require('../../assets/croping/User-2.png'),
   Gemail:require('../../assets/croping/emailg.png'),
   Goback:require('../../assets/croping/Back-Navs2x.png'),
   lp:require('../../assets/croping/Illustration.png'),
   otp:require('../../assets/croping/Illustration-1.png'),

   Desired:require('../../assets/croping/Desired3x.png'),
   inDesired:require('../../assets/croping/inDesired.png'),

   intphoto:require('../../assets/croping/inTurnPhotos.png'),
   tphoto:require('../../assets/croping/TurnPhotos.png'),

   Recipe:require('../../assets/croping/inrecipe.png'),
   inRecipe:require('../../assets/croping/recipe.png'),

   Meal:require('../../assets/croping/MealPlanning.png'),
   inMeal:require('../../assets/croping/inMealPlanning.png'),

   Cook:require('../../assets/croping/CookBook.png'),
   inCook:require('../../assets/croping/inCookBook.png'),

   grocery:require('../../assets/croping/Cart3x.png'),
   ingrocery:require('../../assets/croping/Cart3x.png'),
   menu:require('../../assets/croping/SideMenu3x.png'),
   customThumb:require('../../assets/croping/RangMark2x.png'),
   mic:require('../../assets/croping/Voice_13x.png'),
   close:require('../../assets/croping/Close3x.png'),
   back:require('../../assets/croping/Back2x.png'),
   CircleEdit:require('../../assets/croping/Editx.png'),
   bookmark:require('../../assets/croping/Bookmark2x.png'),
   share:require('../../assets/croping/Send2x.png'),
   Add:require('../../assets/croping/Add3x.png'),
   shareLink:require('../../assets/croping/sharelink.png'),
   shareApp:require('../../assets/croping/ShareHackaplate.png'),
   dish:require('../../assets/croping/image10.png'),
   camera:require('../../assets/croping/Camera2x.png'),
   image:require('../../assets/croping/Image2x.png'),
   microphon:require('../../assets/croping/Voice2x.png'),
   camera2:require('../../assets/croping/Camera_x.png'),
   book:require('../../assets/croping/Book2x.png'),
   circleDot:require('../../assets/croping/more3x.png'),
   breakfast:require('../../assets/croping/breakfast2x.png'),
   dinner2x:require('../../assets/croping/dinner2x.png'),
   lunch:require('../../assets/croping/lunch2x.png'),
   snacks:require('../../assets/croping/snacks2x.png'),
   Viewgrocery:require('../../assets/croping/Viewgrocery.png'),
   changepass:require('../../assets/croping/Changepas2.png'),
   pluse_circle:require('../../assets/croping/pluse-circle.png'),
   shareapp:require('../../assets/croping/shareapp.png'),
   delete:require('../../assets/croping/Delete.png'),
   tam:require('../../assets/croping/tam.png'),
   cab:require('../../assets/croping/cab.png'),
   fin:require('../../assets/croping/fin.png'),
   on:require('../../assets/croping/on.png'),
   alu:require('../../assets/croping/al.png'),
   share2:require('../../assets/croping/share2.png'),
   G_list:require('../../assets/croping/groceryl.png'),
   Refresh:require('../../assets/croping/refresh.png'),



   
   
}